# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161009_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='president',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
